-- https://github.com/metabrainz/musicbrainz-server/blob/master/admin/sql/CreateTables.sql

CREATE TABLE tag ( -- replicate (verbose)
    id                  SERIAL,
    name                VARCHAR(255) NOT NULL,
    ref_count           INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE release_group_meta ( -- replicate
    id                  INTEGER NOT NULL, -- PK, references release_group.id CASCADE
    release_count       INTEGER NOT NULL DEFAULT 0,
    first_release_date_year   SMALLINT,
    first_release_date_month  SMALLINT,
    first_release_date_day    SMALLINT,
    rating              SMALLINT,
    rating_count        INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE release_group_tag ( -- replicate (verbose)
    release_group       INTEGER NOT NULL, -- PK, references release_group.id
    tag                 INTEGER NOT NULL, -- PK, references tag.id
    count               INTEGER NOT NULL,
    last_updated        TIMESTAMP,
    PRIMARY KEY (release_group, tag)
);

CREATE INDEX release_group_tag_idx_tag ON release_group_tag (tag);

CREATE TABLE release_group ( -- replicate (verbose)
    id                  SERIAL,
    gid                 UUID NOT NULL,
    name                VARCHAR NOT NULL,
    artist_credit       INTEGER NOT NULL, -- references artist_credit.id
    type                INTEGER, -- references release_group_primary_type.id
    comment             VARCHAR(255) NOT NULL DEFAULT '',
    edits_pending       INTEGER NOT NULL DEFAULT 0,
    last_updated        TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE artist ( -- replicate (verbose)
    id                  SERIAL,
    gid                 UUID NOT NULL,
    name                VARCHAR NOT NULL,
    sort_name           VARCHAR NOT NULL,
    begin_date_year     SMALLINT,
    begin_date_month    SMALLINT,
    begin_date_day      SMALLINT,
    end_date_year       SMALLINT,
    end_date_month      SMALLINT,
    end_date_day        SMALLINT,
    type                INTEGER, -- references artist_type.id
    area                INTEGER, -- references area.id
    gender              INTEGER, -- references gender.id
    comment             VARCHAR(255) NOT NULL DEFAULT '',
    edits_pending       INTEGER NOT NULL DEFAULT 0,
    last_updated        TIMESTAMP,
    ended               BOOLEAN NOT NULL DEFAULT FALSE,
    begin_area          INTEGER, -- references area.id
    end_area            INTEGER, -- references area.id
    PRIMARY KEY (id)
);

CREATE TABLE artist_credit ( -- replicate
    id                  SERIAL,
    name                VARCHAR NOT NULL,
    artist_count        SMALLINT NOT NULL,
    ref_count           INTEGER DEFAULT 0,
    created             TIMESTAMP,
    edits_pending       INTEGER NOT NULL DEFAULT 0,
    gid                 UUID NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE genre ( -- replicate (verbose)
    id                  SERIAL, -- PK
    gid                 UUID NOT NULL,
    name                VARCHAR NOT NULL,
    comment             VARCHAR(255) NOT NULL DEFAULT '',
    edits_pending       INTEGER NOT NULL DEFAULT 0,
    last_updated        TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE link ( -- replicate
    id                  SERIAL,
    link_type           INTEGER NOT NULL, -- references link_type.id
    begin_date_year     SMALLINT,
    begin_date_month    SMALLINT,
    begin_date_day      SMALLINT,
    end_date_year       SMALLINT,
    end_date_month      SMALLINT,
    end_date_day        SMALLINT,
    attribute_count     INTEGER NOT NULL DEFAULT 0,
    created             TIMESTAMP,
    ended               BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);

CREATE INDEX link_idx_type ON link (link_type);

-- https://github.com/metabrainz/musicbrainz-server/blob/master/admin/sql/caa/CreateTables.sql

CREATE TABLE cover_art ( -- replicate (verbose)
    id BIGINT NOT NULL, -- PK
    release INTEGER NOT NULL, -- references musicbrainz.release.id CASCADE
    comment TEXT NOT NULL DEFAULT '',
    edit INTEGER NOT NULL, -- separately references musicbrainz.edit.id
    ordering INTEGER NOT NULL CHECK (ordering > 0),
    date_uploaded TIMESTAMP NOT NULL,
    edits_pending INTEGER NOT NULL DEFAULT 0 CHECK (edits_pending >= 0),
    mime_type TEXT NOT NULL, -- references cover_art_archive.image_type.mime_type
    filesize INTEGER,
    thumb_250_filesize INTEGER,
    thumb_500_filesize INTEGER,
    thumb_1200_filesize INTEGER,
    PRIMARY KEY (id)
);

CREATE INDEX cover_art_idx_release ON cover_art (release);

CREATE TABLE exclude_release_groups (
    gid UUID NOT NULL,
    PRIMARY KEY (gid)
);

INSERT INTO exclude_release_groups VALUES
-- SB19
('9bdcd649-cfce-4aeb-a537-d6e3bad13486'),
('28766261-cd2d-4f6d-905a-185bf40c96b1'),
('fac9772d-a91d-41d7-9c03-c21807cef04d');

CREATE TABLE genre_parents (
    parent_genre VARCHAR NOT NULL,
    child_genre VARCHAR NOT NULL,
    PRIMARY KEY (parent_genre, child_genre)
);

INSERT INTO genre_parents VALUES
('ambient', 'ambient americana'),
('ambient', 'space ambient'),
('ambient', 'tribal ambient'),
('blues', 'acoustic blues'),
('blues', 'african blues'),
('blues', 'boogie-woogie'),
('blues', 'british blues'),
('blues', 'chicago blues'),
('blues', 'classic blues'),
('blues', 'country blues'),
('blues', 'delta blues'),
('blues', 'electric blues'),
('blues', 'hill country blues'),
('blues', 'jump blues'),
('blues', 'louisiana blues'),
('blues', 'modern blues'),
('blues', 'new orleans blues'),
('blues', 'piano blues'),
('blues', 'soul blues'),
('blues', 'texas blues'),
('classical', 'art song'),
('classical', 'ballet'),
('classical', 'baroque'),
('classical', 'cantata'),
('classical', 'contemporary classical'),
('classical', 'impressionism'),
('classical', 'madrigal'),
('classical', 'march'),
('classical', 'mass'),
('classical', 'modern classical'),
('classical', 'motet'),
('classical', 'neoclassicism'),
('classical', 'opera'),
('classical', 'renaissance'),
('classical', 'romantic classical'),
('classical', 'symphony'),
('classical', 'zarzuela'),
('comedy', 'break-in'),
('comedy', 'prank calls'),
('comedy', 'sketch comedy'),
('comedy', 'standup comedy'),
('country', 'alternative country'),
('country', 'bakersfield sound'),
('country', 'bluegrass'),
('country', 'classic country'),
('country', 'contemporary country'),
('country', 'country yodeling'),
('country', 'honky tonk'),
('country', 'nashville sound'),
('country', 'progressive country'),
('country', 'red dirt'),
('country', 'texas country'),
('country', 'traditional country'),
('country', 'truck driving country'),
('country', 'urban cowboy'),
('country', 'western'),
('country', 'western swing'),
('dance', 'electro'),
('dance', 'eurobeat'),
('dance', 'eurodance'),
('electronic', 'algorave'),
('electronic', 'bit music'),
('electronic', 'celtic electronica'),
('electronic', 'chillsynth'),
('electronic', 'club'),
('electronic', 'digital fusion'),
('electronic', 'downtempo'),
('electronic', 'drift phonk'),
('electronic', 'dungeon synth'),
('electronic', 'edm'),
('electronic', 'electronica'),
('electronic', 'experimental electronic'),
('electronic', 'flashcore'),
('electronic', 'folktronica'),
('electronic', 'funktronica'),
('electronic', 'futurepop'),
('electronic', 'glitch'),
('electronic', 'hexd'),
('electronic', 'horror synth'),
('electronic', 'idm'),
('electronic', 'illbient'),
('electronic', 'indietronica'),
('electronic', 'leftfield'),
('electronic', 'microsound'),
('electronic', 'minatory'),
('electronic', 'minimal wave'),
('electronic', 'moogsploitation'),
('electronic', 'nightcore'),
('electronic', 'nu disco'),
('electronic', 'nu jazz'),
('electronic', 'progressive electronic'),
('electronic', 'psybient'),
('electronic', 'seapunk'),
('electronic', 'synthwave'),
('electronic', 'vaporwave'),
('electronic', 'wave'),
('electronic', 'witch house'),
('experimental', 'noise'),
('experimental', 'plunderphonics'),
('experimental', 'reductionism'),
('experimental', 'sound art'),
('experimental', 'sound collage'),
('edm', 'artcore'),
('edm', 'balani show'),
('edm', 'baltimore club'),
('edm', 'bérite club'),
('edm', 'breakbeat'),
('edm', 'breakcore'),
('edm', 'broken beat'),
('edm', 'bubblegum bass'),
('edm', 'bubbling'),
('edm', 'budots'),
('edm', 'coupé-décalé'),
('edm', 'deconstructed club'),
('edm', 'drum and bass'),
('edm', 'dubstep'),
('edm', 'electro latino'),
('edm', 'electroclash'),
('edm', 'footwork'),
('edm', 'footwork jungle'),
('edm', 'freestyle'),
('edm', 'funkot'),
('edm', 'future bass'),
('edm', 'future rave'),
('edm', 'ghettotech'),
('edm', 'grime'),
('edm', 'hands up'),
('edm', 'hard drum'),
('edm', 'hard nrg'),
('edm', 'hardcore techno'),
('edm', 'hardstyle'),
('edm', 'house'),
('edm', 'jersey club'),
('edm', 'jumpstyle'),
('edm', 'jungle terror'),
('edm', 'kuduro'),
('edm', 'lento violento'),
('edm', 'manyao'),
('edm', 'midtempo bass'),
('edm', 'moombahcore'),
('edm', 'moombahton'),
('edm', 'nerdcore techno'),
('edm', 'nortec'),
('edm', 'philly club'),
('edm', 'rave'),
('edm', 'shangaan electro'),
('edm', 'singeli'),
('edm', 'spacesynth'),
('edm', 'techno'),
('edm', 'trance'),
('edm', 'trap edm'),
('edm', 'tribal guarachero'),
('edm', 'uk funky'),
('edm', 'uk garage'),
('field recording', 'nature sounds'),
('folk', 'appalachian folk'),
('folk', 'bagad'),
('folk', 'celtic'),
('folk', 'contemporary folk'),
('folk', 'neo-medieval folk'),
('folk', 'old-time'),
('folk', 'pagan folk'),
('folk', 'scrumpy and western'),
('folk', 'sea shanty'),
('folk', 'seguidilla'),
('folk', 'sevdalinka'),
('folk', 'sevillanas'),
('folk', 'skiffle'),
('folk', 'stornello'),
('folk', 'sutartinės'),
('folk', 'tajaraste'),
('folk', 'talking blues'),
('folk', 'tarantella'),
('folk', 'visa'),
('folk', 'waulking song'),
('folk', 'yodeling'),
('hip hop', 'abstract hip hop'),
('hip hop', 'afro trap'),
('hip hop', 'afroswing'),
('hip hop', 'alternative hip hop'),
('hip hop', 'arabesk rap'),
('hip hop', 'battle rap'),
('hip hop', 'bongo flava'),
('hip hop', 'boom bap'),
('hip hop', 'bounce'),
('hip hop', 'chicano rap'),
('hip hop', 'chipmunk soul'),
('hip hop', 'chopped and screwed'),
('hip hop', 'christian hip hop'),
('hip hop', 'cloud rap'),
('hip hop', 'comedy hip hop'),
('hip hop', 'conscious hip hop'),
('hip hop', 'crunk'),
('hip hop', 'digicore'),
('hip hop', 'drumless hip hop'),
('hip hop', 'east coast hip hop'),
('hip hop', 'experimental hip hop'),
('hip hop', 'g-funk'),
('hip hop', 'gangsta rap'),
('hip hop', 'genge'),
('hip hop', 'hardcore hip hop'),
('hip hop', 'hiplife'),
('hip hop', 'horrorcore'),
('hip hop', 'hyphy'),
('hip hop', 'instrumental hip hop'),
('hip hop', 'jazz rap'),
('hip hop', 'jerk rap'),
('hip hop', 'miami bass'),
('hip hop', 'mobb music'),
('hip hop', 'nerdcore'),
('hip hop', 'old school hip hop'),
('hip hop', 'phonk'),
('hip hop', 'political hip hop'),
('hip hop', 'pop rap'),
('hip hop', 'punk rap'),
('hip hop', 'snap'),
('hip hop', 'southern hip hop'),
('hip hop', 'trap'),
('hip hop', 'turntablism'),
('hip hop', 'underground hip hop'),
('hip hop', 'west coast hip hop'),
('industrial', 'death industrial'),
('industrial', 'electro-industrial'),
('industrial', 'post-industrial'),
('jazz', 'afro-jazz'),
('jazz', 'avant-garde jazz'),
('jazz', 'bebop'),
('jazz', 'big band'),
('jazz', 'cape jazz'),
('jazz', 'classic jazz'),
('jazz', 'contemporary jazz'),
('jazz', 'cool jazz'),
('jazz', 'crime jazz'),
('jazz', 'crossover jazz'),
('jazz', 'dark jazz'),
('jazz', 'dixieland'),
('jazz', 'ethio-jazz'),
('jazz', 'free jazz'),
('jazz', 'gypsy jazz'),
('jazz', 'hard bop'),
('jazz', 'instrumental jazz'),
('jazz', 'jazz fusion'),
('jazz', 'jazz-funk'),
('jazz', 'latin jazz'),
('jazz', 'marabi'),
('jazz', 'modal jazz'),
('jazz', 'orchestral jazz'),
('jazz', 'post-bop'),
('jazz', 'smooth jazz'),
('jazz', 'soul jazz'),
('jazz', 'stride'),
('jazz', 'swing'),
('jazz', 'vocal jazz'),
('metal', 'alternative metal'),
('metal', 'avant-garde metal'),
('metal', 'black metal'),
('metal', 'christian metal'),
('metal', 'death metal'),
('metal', 'doom metal'),
('metal', 'drone metal'),
('metal', 'folk metal'),
('metal', 'gothic metal'),
('metal', 'groove metal'),
('metal', 'heavy metal'),
('metal', 'kawaii metal'),
('metal', 'neoclassical metal'),
('metal', 'pop metal'),
('metal', 'post-metal'),
('metal', 'power metal'),
('metal', 'progressive metal'),
('metal', 'sludge metal'),
('metal', 'southern metal'),
('metal', 'stoner metal'),
('metal', 'symphonic metal'),
('metal', 'thrash metal'),
('metal', 'trance metal'),
('metal', 'viking metal'),
('musical', 'cabaret'),
('musical', 'industrial musical'),
('musical', 'murga'),
('musical', 'music hall'),
('musical', 'rock musical'),
('musical', 'vaudeville'),
('new age', 'celtic new age'),
('new age', 'neoclassical new age'),
('psychedelic', 'burmese stereo'),
('psychedelic', 'freakbeat'),
('psychedelic', 'psychedelic folk'),
('psychedelic', 'psychedelic pop'),
('psychedelic', 'psychedelic rock'),
('punk', 'alternative punk'),
('punk', 'anarcho-punk'),
('punk', 'art punk'),
('punk', 'cowpunk'),
('punk', 'electropunk'),
('punk', 'folk punk'),
('punk', 'post-hardcore'),
('punk', 'punk rock'),
('r&b', 'blue-eyed soul'),
('r&b', 'british rhythm & blues'),
('r&b', 'contemporary r&b'),
('r&b', 'doo-wop'),
('r&b', 'new orleans r&b'),
('r&b', 'quiet storm'),
('r&b', 'swamp pop'),
('singer-songwriter', 'avtorskaya pesnya'),
('singer-songwriter', 'euskal kantagintza berria'),
('singer-songwriter', 'kleinkunst'),
('singer-songwriter', 'liedermacher'),
('singer-songwriter', 'música de intervenção'),
('singer-songwriter', 'nova cançó'),
('singer-songwriter', 'nueva canción'),
('ska', '2 tone'),
('ska', 'jamaican ska'),
('ska', 'third wave ska'),
('spoken word', 'fairy tale'),
('spoken word', 'guided meditation'),
('spoken word', 'interview'),
('spoken word', 'lecture'),
('spoken word', 'speech'),
('trance', 'acid trance'),
('trance', 'ambient trance'),
('trance', 'dream trance'),
('trance', 'euro-trance'),
('trance', 'goa trance'),
('trance', 'hard trance'),
('trance', 'melodic trance'),
('trance', 'progressive trance'),
('trance', 'psytrance'),
('trance', 'tech trance'),
('trance', 'vocal trance'),
('psytrance', 'dark psytrance'),
('rock', 'acoustic rock'),
('rock', 'afro rock'),
('rock', 'alternative rock'),
('rock', 'anatolian rock'),
('rock', 'aor'),
('rock', 'arena rock'),
('rock', 'art rock'),
('rock', 'christian rock'),
('rock', 'classic rock'),
('rock', 'comedy rock'),
('rock', 'dance-rock'),
('rock', 'experimental rock'),
('rock', 'folk rock'),
('rock', 'freakbeat'),
('rock', 'garage rock'),
('rock', 'glam rock'),
('rock', 'gothic rock'),
('rock', 'hard rock'),
('rock', 'heartland rock'),
('rock', 'instrumental rock'),
('rock', 'jam band'),
('rock', 'jazz rock'),
('rock', 'latin rock'),
('rock', 'mainstream rock'),
('rock', 'mangue beat'),
('rock', 'math rock'),
('rock', 'miejski folk'),
('rock', 'mod'),
('rock', 'neo-rockabilly'),
('rock', 'new wave'),
('rock', 'noise rock'),
('rock', 'occult rock'),
('rock', 'piano rock'),
('rock', 'pop yeh-yeh'),
('rock', 'post-punk'),
('rock', 'post-rock'),
('rock', 'progressive rock'),
('rock', 'proto-punk'),
('rock', 'psychedelic rock'),
('rock', 'pub rock'),
('rock', 'punk blues'),
('rock', 'rautalanka'),
('rock', 'rock and roll'),
('rock', 'rock andaluz'),
('rock', 'rock andino'),
('rock', 'rock opera'),
('rock', 'rock urbano'),
('rock', 'roots rock'),
('rock', 'soft rock'),
('rock', 'southern rock'),
('rock', 'sufi rock'),
('rock', 'surf'),
('rock', 'swamp rock'),
('rock', 'symphonic rock'),
('rock', 'visual kei'),
('rock', 'zolo'),
('pop', 'alternative pop'),
('pop', 'ambient pop'),
('pop', 'art pop'),
('pop', 'avant-garde pop'),
('pop', 'bardcore'),
('pop', 'baroque pop'),
('pop', 'brill building'),
('pop', 'bubblegum pop'),
('pop', 'c-pop'),
('pop', 'canción melódica'),
('pop', 'city pop'),
('pop', 'classical crossover'),
('pop', 'contemporary christian'),
('pop', 'dance-pop'),
('pop', 'dansband'),
('pop', 'denpa'),
('pop', 'easy listening'),
('pop', 'electropop'),
('pop', 'europop'),
('pop', 'flamenco pop'),
('pop', 'hyperpop'),
('pop', 'hypnagogic pop'),
('pop', 'indian pop'),
('pop', 'indie pop'),
('pop', 'j-pop'),
('pop', 'jazz pop'),
('pop', 'k-pop'),
('pop', 'kayōkyoku'),
('pop', 'korean ballad'),
('pop', 'latin pop'),
('pop', 'levenslied'),
('pop', 'mulatós'),
('pop', 'nederpop'),
('pop', 'neo-acoustic'),
('pop', 'nyū myūjikku'),
('pop', 'operatic pop'),
('pop', 'persian pop'),
('pop', 'pop ghazal'),
('pop', 'progressive pop'),
('pop', 'psychedelic pop'),
('pop', 'q-pop'),
('pop', 'rom kbach'),
('pop', 'russian chanson'),
('pop', 'schlager'),
('pop', 'shibuya-kei'),
('pop', 'sophisti-pop'),
('pop', 'sundanese pop'),
('pop', 'synth-pop'),
('pop', 'teen pop'),
('pop', 'v-pop'),
('pop', 'wong shadow'),
('pop', 'yé-yé');
