org: elliotchance
app: chartbrainz
service: chartbrainz
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  customDomain:
    domainName: ${sls:stage}.chartbrainz.com
    basePath: ''
    stage: ${sls:stage}
    createRoute53Record: true

package:
   include:
      - handlers/**
      - node_modules/**
      - dist/**
   exclude:
      - "**"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  environment:
    # If you get an error here when running locally, make sure you run:
    #   make config/local.json
    OAUTH_CLIENT_ID: ${file(./config/${sls:stage}.json):OAuthClientID}
    OAUTH_CLIENT_SECRET: ${file(./config/${sls:stage}.json):OAuthClientSecret}
    OAUTH_REDIRECT_URI: ${file(./config/${sls:stage}.json):OAuthRedirectURI}
    BACKEND_DOMAIN: ${file(./config/${sls:stage}.json):BackendDomain}
    FRONTEND_DOMAIN: ${file(./config/${sls:stage}.json):FrontendDomain}
    SUPABASE_KEY: ${file(./config/${sls:stage}.json):SupabaseKey}
    SUPABASE_URL: ${file(./config/${sls:stage}.json):SupabaseURL}

functions:
  login:
    handler: handlers/login.handler
    events:
      - http:
          path: /login
          method: get

  logout:
    handler: handlers/logout.handler
    events:
      - http:
          path: /logout
          method: get

  oauth:
    handler: handlers/oauth.handler
    events:
      - http:
          path: /oauth
          method: get

  static:
    handler: handlers/static.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /assets/{any+}
          method: get
      - http:
          path: /static/{any+}
          method: get

  fetch-ratings:
    handler: handlers/fetch-ratings.handler
    events:
      - http:
          path: /fetch-ratings
          method: get

  sync-ratings:
    handler: handlers/sync-ratings.handler
    timeout: 30
    events:
      - http:
          path: /sync-ratings
          method: get

  refresh-token:
    handler: handlers/refresh-token.handler
    events:
      - http:
          path: /refresh-token
          method: get
